### ISSUE TITLE
Installation fails on Windows with Python 3.5.1 due to Sharp dependency

### ISSUE THREAD

**Issue by nashv** [nicolaspanel/numjs#2]
Log below.

```

> gyp ERR! configure error
> gyp ERR! stack Error: Python executable "C:\Python35\python.EXE" is v3.5.1, which is not supported by gyp.
> gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
> gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
> gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:395:9
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:193:7)
> gyp ERR! stack     at emitTwo (events.js:100:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
> gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
> gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
> gyp ERR! stack     at emitOne (events.js:90:13)
> gyp ERR! stack     at Socket.emit (events.js:182:7)
> gyp ERR! stack     at Pipe._onclose (net.js:475:12)
> gyp ERR! System Windows_NT 10.0.10586
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\nash\node_modules\sharp
> gyp ERR! node -v v5.7.0
> gyp ERR! node-gyp -v v3.2.1
> gyp ERR! not ok
> npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\nash\package.json'
> npm WARN nash No description
> npm WARN nash No repository field.
> npm WARN nash No README data
> npm WARN nash No license field.
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sharp"
> npm ERR! node v5.7.0
> npm ERR! npm  v3.6.0
> npm ERR! code ELIFECYCLE
> 
> npm ERR! sharp@0.14.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the sharp@0.14.1 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the sharp package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs sharp
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls sharp
> npm ERR! There is likely additional logging output above.

```

**Comment by nicolaspanel** [comment]
have you tried [this](http://stackoverflow.com/questions/20454199/how-to-use-a-different-version-of-python-during-npm-install?answertab=votes#tab-top)?

**Comment by nicolaspanel** [comment]
BTW, the error come from [sharp](https://github.com/lovell/sharp) dependency => You should get in touch with them instead If the solution above does not work.
BR

**Comment by alexlapinski** [comment]
I ran into this issue as well, and I attempted to install the latest version of sharp (0.16.2) and that version of sharp installed fine. While installing '0.15.1' the dependency in this package did not work.

I'm on OSX, not windows, but found this issue by searching related to the same error message.

**Comment by nicolaspanel** [comment]
could you try `npm install sharp` ?
If it fail, make sure following requirements are satisfied on your machine: 
 -  C++11 compatible compiler such as gcc 4.8+, clang 3.0+ or MSVC 2013+
 - [node-gyp](https://github.com/nodejs/node-gyp) and its dependencies
