### ISSUE TITLE
Error installing the module

### ISSUE THREAD

**Issue by prashant45** [nicolaspanel/numjs#24]
I am getting the following error while installing this lib. I don't seem to get the hang of what is the exact problem

```shell
$ npm i numjs

> deasync@0.1.10 install C:\Users\Prashant\abc\node_modules\deasync
> node ./build.js

`win32-x64-node-8` exists; testing
Binary is fine; exiting

> sharp@0.17.3 install C:\Users\Prashant\abc\node_modules\sharp
> node-gyp rebuild


C:\Users\Prashant\abc\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: ENOENT: no such file or directory, open 'C:\Program'
gyp ERR! stack     at Object.fs.openSync (fs.js:652:18)
gyp ERR! stack     at Object.fs.readFileSync (fs.js:553:33)
gyp ERR! stack     at readCAFile (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:466:15)
gyp ERR! stack     at download (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:438:22)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:185:19
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:48:26
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:5)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Prashant\abc\node_modules\sharp
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN gaitToolbox@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.17.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Prashant\AppData\Roaming\npm-cache\_logs\2017-08-31T12_53_03_906Z-debug.log
```

Any clue ?
Also, do I need python for installing this library?

**Comment by nicolaspanel** [comment]
build error comes from [sharp](https://github.com/lovell/sharp)

take a look to https://github.com/lovell/sharp/search?q=no+such+file+or+directory%2C+open+%27C%3A%5CProgram%27&type=Issues&utf8=%E2%9C%93
