### ISSUE TITLE
Reshape Not allowing resizing

### ISSUE THREAD

**Issue by MasterJames** [nicolaspanel/numjs#46]
Doing a little REPL testing I found the reshape commend is not working.

> let rangeArray = np.arange(6,12)
> rangeArray
array([  6,  7,  8,  9, 10, 11])

> rangeArray.reshape( (2,3) )
ValueError: total size of new array must be unchanged
    at new ValueError (./node_modules/numjs/src/errors.js:5:21)
    at NdArray.reshape (./node_modules/numjs/src/ndarray.js:260:11)
> rangeArray.size
6
> rangeArray.reshape( (1,6) )
array([  6,  7,  8,  9, 10, 11])
> rangeArray.reshape( (6,1) )
ValueError: total size of new array must be unchanged
    at new ValueError (./node_modules/numjs/src/errors.js:5:21)
    at NdArray.reshape (./node_modules/numjs/src/ndarray.js:260:11)

**Comment by MasterJames** [comment]
Right sorry thanks for taken the time. I'm just looking through a python tutorial and wanting to use JavaScript so I overlooked it being an eager noob.
square brackets in reshape! I over looked it thanks for the helpful link.

```
> let ra = np.arange(6,12)
> ra
array([  6,  7,  8,  9, 10, 11])
> ra.reshape( (2,3) )
ValueError: total size of new array must be unchanged
    at new ValueError (./node_modules/numjs/src/errors.js:5:21)
    at NdArray.reshape (./node_modules/numjs/src/ndarray.js:260:11)
> ra.reshape( **[**2,3**]** )
array([[  6,  7,  8],
       [  9, 10, 11]])
>
```
